apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: keycloak
  namespace: keycloak
spec:
  host: keycloak.nginx.rocks
  tls:
    secret: nginx-rocks-tls
    redirect:
      enable: true
  upstreams:
    - name: keycloak
      service: keycloak
      port: 8080
  routes:
    - path: /
      action:
        pass: keycloak