---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: webapp
type: nginx.org/oidc
data:
  client-secret: "SECRETKEY"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
  namespace: webapp
spec:
  oidc:
    clientID: nginx-plus
    clientSecret: oidc-secret
    authEndpoint: https://keycloak.nginx.rocks/auth/realms/master/protocol/openid-connect/auth
    tokenEndpoint: http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/token
    jwksURI: http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/master/protocol/openid-connect/certs
    scope: openid+profile+email
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
  namespace: webapp
spec:
  host: webapp.nginx.rocks
  tls:
    secret: nginx-rocks-tls
    redirect:
      enable: true
  upstreams:
    - name: webapp
      service: webapp-svc
      port: 80
  routes:
    - path: /
      policies:
      - name: oidc-policy
      action:
        pass: webapp